<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-md-12 col-sm-12">
            <code>Route:: /Contact</code>
            <hr>
            <div class="panel panel-default">
                <div class="panel-body">
                    <p>Id: <strong><?= $this->view->client['id'] ?></strong></p>
                    <p>Name: <strong><?= $this->view->client['name'] ?></strong></p>
                    <p>Website: <strong><?= $this->view->client['website'] ?></strong></p>
                </div>
            </div>
        </div>
    </div>
</div>
