<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-md-12 col-sm-12">
            <code>Route:: /</code>
            <hr>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Website</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->view->clients as $key => $item): ?>
                    <tr>
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['name'] ?></td>
                        <td><?= $item['website'] ?></td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>
